---

namespace: "redhat_cop"
name: "tower_genie_collections"
version: "0.1"
readme: "README.md"
authors:
    - "Andrew Huffman"
    - "Jonathan Lozada De La Matta"
license:
    - "GPLv3"
tags:
    - tower
    - collection
    - genie
repository: "https://www.github.com/redhat-cop/tower_genie_collections"
# documentation: "http://my-docs.example.com"
# homepage: "http://www.example.com"
issues: "https://www.github.com/redhat-cop/tower_genie_collections/issues"
