---
namespace: redhat_cop
name: tower_configuration
version: 0.2.0
description: A collection of roles to manage Ansible Tower
readme: README.md
authors:
    - Andrew Huffman
    - Jonathan Lozada De La Matta @jlozadad
    - Kedar Kulkarni @kedark3
    - Tom Page @Tompage1994
    - Sean Sullivan @sean-m-sullivan
repository: https://github.com/redhat-cop/tower_configuration
issues: https://github.com/redhat-cop/tower_configuration/issues
build_ignore:
    - galaxy.yml.j2
    - release.yml
    - .github
    - .ansiblelint.yml
    - .yamllint.yml
license:
    - GPL-3.0-or-later
tags:
    - tower
    - collection
    - tower_configuration
dependencies:
    awx.awx: "*"
