---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/adrienverge/yamllint.git'
    rev: v1.25.0
    hooks:
      - id: yamllint
        entry: yamllint -c .github/workflow-config/.yamllint.yml
        types:
          - yaml
  - repo: 'https://github.com/sean-m-sullivan/ansible-lint.git'
    rev: v5.0.0b
#  - repo: 'https://github.com/ansible-community/ansible-lint.git'
#    rev: v5.0.0a0
    hooks:
      # see discussions here about what arguments are used, and behavior
      # https://github.com/ansible/ansible-lint/issues/649
      # Roles will trigger an "unknown file type"
      # https://github.com/ansible/ansible-lint/issues/808
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: >-
          ansible-lint -vp -c .github/workflow-config/.ansiblelint.yml
          --exclude=temp_test_module.yml
          --exclude=roles/namespace/tasks/main.yml
          --exclude=playbooks/testing_playbook.yml
          --exclude=playbooks/ah_configs/ah_namespaces.yml
