---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/adrienverge/yamllint.git'
    rev: v1.26.0
    hooks:
      - id: yamllint
        entry: yamllint -c .github/workflow-config/.yamllint.yml
        types:
          - yaml
  - repo: 'https://github.com/ansible-community/ansible-lint.git'
    rev: v5.0.0
    #  - repo: 'https://github.com/ansible-community/ansible-lint.git'
    #    rev: v5.0.0a0
    #  - repo: 'https://github.com/sean-m-sullivan/ansible-lint.git'
    #    rev: v5.0.0b
    hooks:
      # see discussions here about what arguments are used, and behavior
      # https://github.com/ansible/ansible-lint/issues/649
      # Roles will trigger an "unknown file type"
      # https://github.com/ansible/ansible-lint/issues/808
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: >-
          ansible-lint -vp -c .github/workflow-config/.ansiblelint.yml
#          --exclude=temp_test_module.yml
#          --exclude=playbooks/testing_playbook.yml
#          --exclude=playbooks/ah_configs/
#          --exclude=playbooks/test_collection/galaxy.yml
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        name: black
        language_version: python3.9
        entry: black
        args: [--config=.github/workflow-config/black.cfg, --check, --diff]
        types: [python]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        args: [--config=.github/workflow-config/flake8.cfg]
        types: [python]
...
