---
- name: "Get the Tower/AAP instance version"
  ansible.builtin.set_fact:
    aap_version: "{{ lookup(controller_api_plugin, 'ping',
                       host=aap_hostname, oauth_token=aap_oauthtoken,
                       verify_ssl=controller_validate_certs).version }}"
- name: "Check if the connection is to an Ansible Tower or to Automation Platform"
  ansible.builtin.set_fact:
    is_aap: "{{ aap_version is version('4.0.0', '>=') }}"
    have_constructed: "{{ aap_version is version('4.5.0', '>=') }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: "Block to get the organization_filter ID to filter all the queries"
  when:
    - organization_filter is defined
    - organization_filter | length > 0
  block:
    - name: "Get the organization_filter ID to restrict the API queries"
      ansible.builtin.set_fact:
        organization_id: "{{ lookup(controller_api_plugin, 'organizations',
                                    query_params={'name': organization_filter},
                                    host=aap_hostname, oauth_token=aap_oauthtoken,
                                    verify_ssl=controller_validate_certs).id
                          }}"
      no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

    - name: "Show the organization_filter ID"
      ansible.builtin.debug:
        msg: "The organization {{ organization_filter }} has the ID {{ organization_id }}"

- name: Include tasks (block)
  when: "['all', 'labels', 'applications', 'instance_groups', 'settings', 'inventory', 'credentials', 'credential_types', 'notification_templates', 'users', 'teams', 'roles', 'organizations', 'projects', 'execution_environments', 'job_templates', 'workflow_job_templates', 'workflow_job_template_nodes', 'schedules'] | intersect(input_tag) | length > 0"
  block:
    - name: "Export Inventories and related Groups and Hosts"
      ansible.builtin.include_tasks: "controller_inventory.yml"
      when: "'inventory' in input_tag or 'all' in input_tag"
    - name: "Export Constructed Inventories"
      ansible.builtin.include_tasks: "controller_constructed_inventory.yml"
      when: "('inventory' in input_tag or 'all' in input_tag) and have_constructed"
    - name: "Export Credentials"
      ansible.builtin.include_tasks: "controller_credentials.yml"
      when: "'credentials' in input_tag or 'all' in input_tag"
    - name: "Export Credential Types"
      ansible.builtin.include_tasks: "controller_credential_types.yml"
      when: "'credential_types' in input_tag or 'all' in input_tag"
    - name: "Export Notification Templates"
      ansible.builtin.include_tasks: "controller_notification_templates.yml"
      when: "'notification_templates' in input_tag or 'all' in input_tag"
    - name: "Export Users"
      ansible.builtin.include_tasks: "controller_users.yml"
      when: "'users' in input_tag or 'roles' in input_tag or 'all' in input_tag"
    - name: "Export Teams"
      ansible.builtin.include_tasks: "controller_teams.yml"
      when: "'teams' in input_tag or 'roles' in input_tag or 'all' in input_tag"
    - name: "Export Organizations"
      ansible.builtin.include_tasks: "controller_organizations.yml"
      when: "'organizations' in input_tag or 'all' in input_tag"
    - name: "Export Job Templates"
      ansible.builtin.include_tasks: "controller_job_templates.yml"
      when: "'job_templates' in input_tag or 'all' in input_tag"
    - name: "Export Projects"
      ansible.builtin.include_tasks: "controller_projects.yml"
      when: "'projects' in input_tag or 'all' in input_tag"
    - name: "Export Execution Environments"
      ansible.builtin.include_tasks: "controller_execution_environments.yml"
      when: "('execution_environments' in input_tag or 'all' in input_tag) and is_aap"
    - name: "Export Workflow Job Templates"
      ansible.builtin.include_tasks: "controller_workflow_job_templates.yml"
      when: "'workflow_job_templates' in input_tag or 'all' in input_tag"
    - name: "Export Settings"
      ansible.builtin.include_tasks: "controller_settings.yml"
      when: "'settings' in input_tag or 'all' in input_tag"
    - name: "Export Instance Groups"
      ansible.builtin.include_tasks: "controller_instance_groups.yml"
      when: "'instance_groups' in input_tag or 'all' in input_tag"
    - name: "Export Applications"
      ansible.builtin.include_tasks: "controller_applications.yml"
      when: "'applications' in input_tag or 'all' in input_tag"
    - name: "Export Labels"
      ansible.builtin.include_tasks: "controller_labels.yml"
      when: "'labels' in input_tag or 'all' in input_tag"
    - name: "Export Schedules"
      ansible.builtin.include_tasks: "controller_schedules.yml"
      when: "'schedules' in input_tag or 'all' in input_tag"
...
