---
- name: "Get the Tower/AAP instance version"
  ansible.builtin.set_fact:
    aap_version: "{{ lookup(controller_api_plugin, 'ping',
                       host=aap_hostname, oauth_token=aap_oauthtoken,
                       verify_ssl=aap_validate_certs).version }}"
- name: "Check if the connection is to an Ansible Tower or to Automation Platform"
  ansible.builtin.set_fact:
    is_aap: "{{ aap_version is version('4.0.0', '>=') }}"
    have_constructed: "{{ aap_version is version('4.5.0', '>=') }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: "Block to get the organization_filter ID to filter all the queries"
  when:
    - organization_filter is defined
    - organization_filter | length > 0
  block:
    - name: "Get the organization_filter ID to restrict the API queries"
      ansible.builtin.set_fact:
        organization_id: "{{ lookup(controller_api_plugin, 'organizations',
                                    query_params={'name': organization_filter},
                                    host=aap_hostname, oauth_token=aap_oauthtoken,
                                    verify_ssl=aap_validate_certs).id
                          }}"
      no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

    - name: "Show the organization_filter ID"
      ansible.builtin.debug:
        msg: "The organization {{ organization_filter }} has the ID {{ organization_id }}"

- name: Include tasks (block)
  when: "['all', 'labels', 'applications', 'instance_groups', 'settings', 'inventory', 'credentials', 'credential_types', 'notification_templates', 'users', 'teams', 'roles', 'organizations', 'projects', 'execution_environments', 'job_templates', 'workflow_job_templates', 'workflow_job_template_nodes', 'schedules', 'authenticators', 'authenticator_maps'] | intersect(input_tag) | length > 0"
  block:
    - name: "Export Controller Inventories and related Groups and Hosts"
      ansible.builtin.include_tasks: "controller_inventory.yml"
      when: "'inventory' in input_tag or 'all' in input_tag"
    - name: "Export Controller Constructed Inventories"
      ansible.builtin.include_tasks: "controller_constructed_inventory.yml"
      when: "('inventory' in input_tag or 'all' in input_tag) and have_constructed"
    - name: "Export Controller Credentials"
      ansible.builtin.include_tasks: "controller_credentials.yml"
      when: "'credentials' in input_tag or 'all' in input_tag"
    - name: "Export Controller Credential Types"
      ansible.builtin.include_tasks: "controller_credential_types.yml"
      when: "'credential_types' in input_tag or 'all' in input_tag"
    - name: "Export Controller Notification Templates"
      ansible.builtin.include_tasks: "controller_notification_templates.yml"
      when: "'notification_templates' in input_tag or 'all' in input_tag"
    # Exported through gateway users - name: "Export Controller Users"
    # Exported through gateway users   ansible.builtin.include_tasks: "controller_users.yml"
    # Exported through gateway users   when: "'users' in input_tag or 'roles' in input_tag or 'all' in input_tag"
    - name: "Export Controller Teams"
      ansible.builtin.include_tasks: "controller_teams.yml"
      when: "'teams' in input_tag or 'roles' in input_tag or 'all' in input_tag"
    - name: "Export Controller Organizations"
      ansible.builtin.include_tasks: "controller_organizations.yml"
      when: "'organizations' in input_tag or 'all' in input_tag"
    - name: "Export Controller Job Templates"
      ansible.builtin.include_tasks: "controller_job_templates.yml"
      when: "'job_templates' in input_tag or 'all' in input_tag"
    - name: "Export Controller Projects"
      ansible.builtin.include_tasks: "controller_projects.yml"
      when: "'projects' in input_tag or 'all' in input_tag"
    - name: "Export Controller Execution Environments"
      ansible.builtin.include_tasks: "controller_execution_environments.yml"
      when: "('execution_environments' in input_tag or 'all' in input_tag) and is_aap"
    - name: "Export Controller Workflow Job Templates"
      ansible.builtin.include_tasks: "controller_workflow_job_templates.yml"
      when: "'workflow_job_templates' in input_tag or 'all' in input_tag"
    - name: "Export Controller Settings"
      ansible.builtin.include_tasks: "controller_settings.yml"
      when: "'settings' in input_tag or 'all' in input_tag"
    - name: "Export Controller Instance Groups"
      ansible.builtin.include_tasks: "controller_instance_groups.yml"
      when: "'instance_groups' in input_tag or 'all' in input_tag"
    - name: "Export Controller Applications"
      ansible.builtin.include_tasks: "controller_applications.yml"
      when: "'applications' in input_tag or 'all' in input_tag"
    - name: "Export Controller Labels"
      ansible.builtin.include_tasks: "controller_labels.yml"
      when: "'labels' in input_tag or 'all' in input_tag"
    - name: "Export Controller Schedules"
      ansible.builtin.include_tasks: "controller_schedules.yml"
      when: "'schedules' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Applications"
      ansible.builtin.include_tasks: "gateway_applications.yml"
      when: "'applications' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Authentication Maps"
      ansible.builtin.include_tasks: "gateway_authenticator_maps.yml"
      when: "'authenticator_maps' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Authentication"
      ansible.builtin.include_tasks: "gateway_authenticators.yml"
      when: "'authenticators' in input_tag or 'all' in input_tag"
    - name: "Export Gateway HTTP Ports"
      ansible.builtin.include_tasks: "gateway_http_ports.yml"
      when: "'http_ports' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Organizations"
      ansible.builtin.include_tasks: "gateway_organizations.yml"
      when: "'organizations' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Role User Assignments"
      ansible.builtin.include_tasks: "gateway_role_user_assignments.yml"
      when: "'role_user_assignments' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Routes"
      ansible.builtin.include_tasks: "gateway_routes.yml"
      when: "'routes' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Service Clusters"
      ansible.builtin.include_tasks: "gateway_service_clusters.yml"
      when: "'service_clusters' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Service Keys"
      ansible.builtin.include_tasks: "gateway_service_keys.yml"
      when: "'service_keys' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Service Nodes"
      ansible.builtin.include_tasks: "gateway_service_nodes.yml"
      when: "'gateway_service_nodes' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Services"
      ansible.builtin.include_tasks: "gateway_services.yml"
      when: "'gateway_services' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Settings"
      ansible.builtin.include_tasks: "gateway_settings.yml"
      when: "'gateway_settings' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Teams"
      ansible.builtin.include_tasks: "gateway_teams.yml"
      when: "'gateway_teams' in input_tag or 'all' in input_tag"
    - name: "Export Gateway Users"
      ansible.builtin.include_tasks: "gateway_users.yml"
      when: "'gateway_users' in input_tag or 'all' in input_tag"
    - name: "Export EDA Credential Types"
      ansible.builtin.include_tasks: "eda_credential_types.yml"
      when: "'eda_credential_types' in input_tag or 'all' in input_tag"
    - name: "Export EDA Credentials"
      ansible.builtin.include_tasks: "eda_credentials.yml"
      when: "'eda_credentials' in input_tag or 'all' in input_tag"
    - name: "Export EDA Decision Environments"
      ansible.builtin.include_tasks: "eda_decision_environments.yml"
      when: "'eda_decision_environments' in input_tag or 'all' in input_tag"
    - name: "Export EDA Event Streams"
      ansible.builtin.include_tasks: "eda_event_streams.yml"
      when: "'eda_event_streams' in input_tag or 'all' in input_tag"
    - name: "Export EDA Projects"
      ansible.builtin.include_tasks: "eda_projects.yml"
      when: "'eda_projects' in input_tag or 'all' in input_tag"
    - name: "Export EDA Rulebook Activations"
      ansible.builtin.include_tasks: "eda_rulebook_activations.yml"
      when: "'eda_rulebook_activations' in input_tag or 'all' in input_tag"
...
