---
- name: "Get current Settings from the API"
  ansible.builtin.set_fact:
    changed_settings: "{{ query(controller_api_plugin, 'api/controller/v2/settings/changed/',
                            host=aap_hostname, oauth_token=aap_oauthtoken, verify_ssl=aap_validate_certs,
                            return_all=true, max_objects=query_controller_api_max_objects)
                       }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: "Create the output directory for controller_settings in {{ output_path }}"
  ansible.builtin.file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current settings to the controller_settings.yaml output file in {{ output_path }}"
  ansible.builtin.template:
    src: "templates/controller_settings.j2"
    dest: "{{ output_path }}/controller_settings.yaml"
    mode: '0644'
...
