---
- name: "Get current Credential Types from the API when AAP"
  ansible.builtin.set_fact:
    credential_types_lookvar: "{{ query(controller_api_plugin, 'api/controller/v2/credential_types/',
                                        query_params={'managed': false},
                                        host=aap_hostname, oauth_token=aap_oauthtoken, verify_ssl=aap_validate_certs,
                                        return_all=true, max_objects=query_controller_api_max_objects)
                               }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"
  when: is_aap

- name: "Get current Credential Types from the API when Tower"
  ansible.builtin.set_fact:
    credential_types_lookvar: "{{ query(controller_api_plugin, 'api/controller/v2/credential_types/',
                                        query_params={'managed_by_tower': false},
                                        host=aap_hostname, oauth_token=aap_oauthtoken, verify_ssl=aap_validate_certs,
                                        return_all=true, max_objects=query_controller_api_max_objects)
                               }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"
  when: not is_aap

- name: "Create the output directory for credential types: {{ output_path }}"
  ansible.builtin.file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current credential types to the credential_types.yaml output file in {{ output_path }}"
  ansible.builtin.template:
    src: "templates/controller_credential_types.j2"
    dest: "{{ output_path }}/controller_credential_types.yaml"
    mode: '0644'
  vars:
    current_credential_types_asset_value: "{{ credential_types_lookvar }}"
...
