---
- name: "Get current Credentials from the API"
  set_fact:
<<<<<<< HEAD
    credentials_lookvar: "{{ query('ansible.controller.controller_api', 'api/v2/credentials/',
                                   query_params={'order_by': 'organization,id'},
                                   host=controller_hostname, oauth_token=oauthtoken, verify_ssl=controller_validate_certs,
                                   return_all=true, max_objects=query_controller_api_max_objects)
                          }}"
=======
    credentials_lookvar: "{{ query(controller_api_plugin, 'api/v2/credentials/', query_params={'order_by': 'organization'}, host=controller_hostname, oauth_token=oauthtoken, verify_ssl=controller_validate_certs, return_all=true, max_objects=query_controller_api_max_objects) }}"
>>>>>>> c1a1936227ebf5173ab8bd205b809de44bc653ba

- name: "Create the output directory for credentials: {{ output_path }}/<ORGANIZATION_NAME>/credentials"
  file:
    path: "{{ output_path }}/{{ needed_path }}/credentials"
    state: directory
    mode: '0755'
  loop: "{{ (credentials_lookvar | map(attribute='summary_fields') | selectattr('organization', 'defined') | map(attribute='organization') | map(attribute='name') | list | flatten | unique)
            + (['ORGANIZATIONLESS'] if ((credentials_lookvar | map(attribute='summary_fields') | selectattr('organization', 'undefined') | list | flatten) | length > 0 ) else [])
         }}"
  loop_control:
    loop_var: needed_path
    label: "{{ output_path }}/{{ needed_path }}/credentials"

- name: "Add current credentials to the output yaml file: {{ output_path }}/<ORGANIZATION_NAME>/credentials"
  template:
    src: "templates/current_credentials.j2"
    dest: "{{ output_path }}/{{ credentials_organization }}/credentials/{{ credentials_id }}_{{ credentials_name }}.yaml"
    mode: '0644'
  vars:
    credentials_organization: "{{ current_credentials_asset_value.summary_fields.organization.name | default('ORGANIZATIONLESS') }}"
    credentials_id: "{{ current_credentials_asset_value.id }}"
    credentials_name: "{{ current_credentials_asset_value.name | regex_replace('/','_') }}"
  loop: "{{ credentials_lookvar }}"
  loop_control:
    loop_var: current_credentials_asset_value
    label: "{{ output_path }}/{{ credentials_organization }}/credentials/{{ credentials_id }}_{{ credentials_name }}.yaml"
...
