---
- name: "Get current Execution Environments from the API"
  set_fact:
    execution_environments_lookvar: "{{ query(controller_api_plugin, 'api/v2/execution_environments/',
                                              host=controller_hostname, oauth_token=oauthtoken, verify_ssl=controller_validate_certs,
                                              return_all=true, max_objects=query_controller_api_max_objects)
                                     }}"

- name: "Create the output directory for execution environments: {{ output_path }}"
  file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current execution environments to the output yaml file: {{ output_path }}/current_execution_environments.yaml"
  template:
    src: "templates/current_execution_environments.j2"
    dest: "{{ output_path }}/current_execution_environments.yaml"
    mode: '0644'
  vars:
    current_execution_environments_asset_value: "{{ execution_environments_lookvar }}"
...
