---
- name: "Get current Authenticators from the Gateway API"
  ansible.builtin.set_fact:
    gateway_authenticators_lookvar: "{{ query('ansible.platform.gateway_api', 'api/gateway/v1/authenticators/',
                                        query_params=(query_params | combine({'id': authenticator_id})) if authenticator_id is defined else query_params,
                                        host=aap_hostname, oauth_token=aap_oauthtoken, verify_ssl=aap_validate_certs,
                                        return_all=true, max_objects=query_controller_api_max_objects)
                                    }}"
  vars:
    query_params:
      order_by: 'id'
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: "Create the output directory for gateway authenticators: {{ output_path }}"
  ansible.builtin.file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current gateway authenticator to the gateway_authenticators.yaml output file in {{ output_path }}"
  ansible.builtin.template:
    src: "templates/gateway_authenticators.j2"
    dest: "{{ output_path }}/gateway_authenticators.yaml"
    mode: '0644'
  vars:
    current_gateway_authenticators_asset_value: "{{ gateway_authenticators_lookvar }}"
...
