---
- name: "Get current Role User Assignments from the Gateway API"
  ansible.builtin.set_fact:
    gateway_role_user_assignments_lookvar: "{{ query('ansible.platform.gateway_api', 'api/gateway/v1/role_user_assignments/',
                                        query_params=(query_params | combine({'id': role_user_assignment_id})) if role_user_assignment_id is defined else query_params,
                                        host=aap_hostname, oauth_token=aap_oauthtoken, verify_ssl=aap_validate_certs,
                                        return_all=true, max_objects=query_controller_api_max_objects)
                                    }}"
  vars:
    query_params:
      order_by: 'id'
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: "Create the output directory for gateway role_user_assignments: {{ output_path }}"
  ansible.builtin.file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current gateway role_user_assignment to the gateway_role_user_assignments.yaml output file in {{ output_path }}"
  ansible.builtin.template:
    src: "templates/gateway_role_user_assignments.j2"
    dest: "{{ output_path }}/gateway_role_user_assignments.yaml"
    mode: '0644'
  vars:
    current_gateway_role_user_assignments_asset_value: "{{ gateway_role_user_assignments_lookvar }}"
...
