---
- name: "Create the output directory for hosts: {{ output_path }}"
  file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current hosts to the output yaml file: {{ output_path }}/current_hosts.yaml"
  template:
    src: "templates/current_hosts.j2"
    dest: "{{ output_path }}/current_hosts.yaml"
    mode: '0644'
  when: current_hosts_asset_value | length > 0
...
