---
- name: "Get current Job Templates from the API"
  set_fact:
    job_templates_lookvar: "{{ query(controller_api_plugin, 'api/v2/job_templates/',
                                     query_params={'order_by': 'organization,id'},
                                     host=controller_hostname, oauth_token=oauthtoken, verify_ssl=controller_validate_certs,
                                     return_all=true, max_objects=query_controller_api_max_objects)
                            }}"

- name: "Create the output directories for job templates: {{ output_path }}/<ORGANIZATION_NAME>"
  file:
    path: "{{ output_path }}/{{ needed_path }}/job_templates"
    state: directory
    mode: '0755'
  loop: "{{ (job_templates_lookvar | map(attribute='summary_fields') | selectattr('organization', 'defined') | map(attribute='organization') | map(attribute='name') | list | flatten | unique)
            + (['ORGANIZATIONLESS'] if ((job_templates_lookvar | map(attribute='summary_fields') | selectattr('organization', 'undefined') | list | flatten) | length > 0 ) else [])
         }}"
  loop_control:
    loop_var: needed_path
    label: "{{ output_path }}/{{ needed_path }}/job_templates"

- name: "Add current job_templates to the output yaml file: {{ output_path }}/<ORGANIZATION_NAME>/job_templates"
  template:
    src: "templates/current_job_templates.j2"
    dest: "{{ output_path }}/{{ job_template_organization }}/job_templates/{{ job_template_id }}_{{ job_template_name }}.yaml"
    mode: '0644'
  vars:
    job_template_organization: "{{ current_job_templates_asset_value.summary_fields.organization.name | default('ORGANIZATIONLESS') }}"
    job_template_id: "{{ current_job_templates_asset_value.id }}"
    job_template_name: "{{ current_job_templates_asset_value.name | regex_replace('/','_') }}"
  loop: "{{ job_templates_lookvar }}"
  loop_control:
    loop_var: current_job_templates_asset_value
    label: "{{ output_path }}/{{ job_template_organization }}/job_templates/{{ job_template_id }}_{{ job_template_name }}.yaml"
...
