---
- name: "OBJECT DIFF: Get the current controller user to determine if it is super-admin"
  set_fact:
    __controller_api_current_user_check_is_admin: "{{ lookup('ansible.controller.controller_api', 'users', query_params={ 'username': controller_username },
        host=controller_hostname, oauth_token=oauthtoken, verify_ssl=false) }}"
- block:
    - name: Get the organization ID
      set_fact:
        __controller_organization_id: "{{ lookup('ansible.controller.controller_api', 'organizations', query_params={ 'name': orgs },
          host=controller_hostname, oauth_token=oauthtoken, verify_ssl=false) }}"

    - name: "OBJECT DIFF: Get the API list of all teams {{ orgs }} Organization"
      set_fact:
        __controller_api_teams: "{{ query('ansible.controller.controller_api', 'teams',
          query_params={ 'organization': __controller_organization_id.id },
          host=controller_hostname, oauth_token=oauthtoken, verify_ssl=false) }}"

    - name: "OBJECT DIFF: Find the difference of Teams between what is on the Controller versus CasC on SCM"
      set_fact:
        __teams_difference: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff',
          api_list=__controller_api_teams, compare_list=controller_teams,
          with_present=false, set_absent=true ) }}"

    - name: "OBJECT DIFF: Sets the difference of Teams between what is on the Controller versus CasC on SCM"
      set_fact:
        controller_teams: "{{ __teams_difference }}"
  when:
    - __controller_api_current_user_check_is_admin.is_superuser
...
