---
# tasks file for controller_ldap_settings
- name: "OBJECT DIFF: Get the current controller user to determine if it is super-admin"
  set_fact:
    __controller_api_current_user_check_is_admin: "{{ lookup('ansible.controller.controller_api', 'users', query_params={ 'username': controller_username },
      host=controller_hostname, oauth_token=oauthtoken, verify_ssl=false) }}"

- name: "OBJECT DIFF: Sets the current controller user to determine if it is super-admin"
  set_fact:
    __controller_api_user_accounts: "{{ query('ansible.controller.controller_api', 'users',
      host=controller_hostname, oauth_token=oauthtoken, verify_ssl=false) }}"

- block:
    - name: "Populate User Accounts list"
      set_fact:
        populate_controller_api_user_accounts_without_external_accounts: "{{ __controller_api_user_accounts | selectattr('external_account', 'none') | list }}"

    - name: "Set User Accounts from API without External Accounts Data Structure"
      set_fact:
        __controller_api_user_accounts: "{{ populate_controller_api_user_accounts_without_external_accounts }}"
      when: populate_controller_api_user_accounts_without_external_accounts is defined

  when:
    - drop_user_external_accounts is defined
    - drop_user_external_accounts

- block:

    - name: "OBJECT DIFF: Find the difference of User Accounts between what is on the Controller versus CasC on SCM"
      set_fact:
        __user_accounts_difference: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff',
          api_list=__controller_api_user_accounts, compare_list=controller_user_accounts,
          with_present=false, set_absent=true ) }}"


    - name: "OBJECT DIFF: Sets the difference of User Accounts between what is on the Controller versus CasC on SCM"
      set_fact:
        controller_user_accounts: "{{ __user_accounts_difference }}"

  when:
    - __controller_api_current_user_check_is_admin.is_superuser

...
