---
- name: "Read Applications definitions"
  include_vars:
    file: "{{ item.src }}"
  with_filetree: "{{ filetree_controller_applications }}"
  when: item.state == 'file'
  register: __contents_filetree_controller_applications

- name: "Populate Applications list"
  set_fact:
    __populate_controller_applications: "{{ (__populate_controller_applications | default([])) + item.ansible_facts.controller_applications }}"
  loop: "{{ __contents_filetree_controller_applications.results }}"
  when: __contents_filetree_controller_applications.results is defined and item.ansible_facts.controller_applications is defined

- name: "Set Applications Data Structure"
  set_fact:
    controller_applications: "{{ __populate_controller_applications }}"
  when: __populate_controller_applications is defined
...
