---
- name: "Read Credential Input Sources definitions"
  include_vars:
    file: "{{ item.src }}"
  with_filetree: "{{ filetree_controller_credential_input_sources }}"
  when: item.state == 'file'
  register: __contents_filetree_controller_credential_input_sources

- name: "Populate Credential Input Sources list"
  set_fact:
    __populate_controller_credential_input_sources: "{{ (__populate_controller_credential_input_sources | default([])) + item.ansible_facts.controller_credential_input_sources }}"
  loop: "{{ __contents_filetree_controller_credential_input_sources.results }}"
  when: __contents_filetree_controller_credential_input_sources.results is defined and item.ansible_facts.controller_credential_input_sources is defined

- name: "Set Credential Input Sources Data Structure"
  set_fact:
    controller_credential_input_sources: "{{ __populate_controller_credential_input_sources }}"
  when: __populate_controller_credential_input_sources is defined
...
