---
- name: "Read Credential_Types definitions"
  include_vars:
    file: "{{ item.src }}"
  with_filetree: "{{ filetree_controller_credential_types }}"
  when: item.state == 'file'
  register: __contents_filetree_controller_credential_types

- name: "Populate Credential_Types list"
  set_fact:
    __populate_controller_credential_types: "{{ (__populate_controller_credential_types | default([])) + item.ansible_facts.controller_credential_types }}"
  loop: "{{ __contents_filetree_controller_credential_types.results }}"
  when: __contents_filetree_controller_credential_types.results is defined and item.ansible_facts.controller_credential_types is defined

- name: "Set Projects Data Structure"
  set_fact:
    controller_credential_types: "{{ __populate_controller_credential_types }}"
  when: __populate_controller_credential_types is defined
...
