---
- name: "Get list of files inside {{ filetree_controller_execution_environments }}"
  find:
    paths: "{{ filetree_controller_execution_environments }}"
    file_type: file
    recurse: yes
  register: __list_files_controller_execution_environments

- name: "Read Execution Environments definitions"
  include_vars:
    file: "{{ item.path }}"
  loop: "{{ __list_files_controller_execution_environments.files }}"
  register: __contents_filetree_controller_execution_environments

- name: "Populate Execution Environments list"
  set_fact:
    __populate_controller_execution_environments: "{{ (__populate_controller_execution_environments | default([])) + item.ansible_facts.controller_execution_environments }}"
  loop: "{{ __contents_filetree_controller_execution_environments.results }}"
  when: __contents_filetree_controller_execution_environments.results is defined and item.ansible_facts.controller_execution_environments is defined

- name: "Set Projects Data Structure"
  set_fact:
    controller_execution_environments: "{{ __populate_controller_execution_environments }}"
  when: __populate_controller_execution_environments is defined
...
