---
- name: "Read Hosts definitions"
  include_vars:
    file: "{{ item.src }}"
  with_filetree: "{{ filetree_controller_hosts }}"
  when: item.state == 'file'
  register: __contents_filetree_controller_hosts

- name: "Populate Hosts list"
  set_fact:
    __populate_controller_hosts: "{{ (__populate_controller_hosts | default([])) + item.ansible_facts.controller_hosts }}"
  loop: "{{ __contents_filetree_controller_hosts.results }}"
  when: __contents_filetree_controller_hosts.results is defined and item.ansible_facts.controller_hosts is defined

- name: "Set Projects Data Structure"
  set_fact:
    controller_hosts: "{{ __populate_controller_hosts }}"
  when: __populate_controller_hosts is defined
...
