---
- name: "Read Instance Groups definitions"
  include_vars:
    file: "{{ item.src }}"
  with_filetree: "{{ filetree_controller_instance_groups }}"
  when: item.state == 'file'
  register: __contents_filetree_controller_instance_groups

- name: "Populate Instance Groups list"
  set_fact:
    __populate_controller_instance_groups: "{{ (__populate_controller_instance_groups | default([])) + item.ansible_facts.controller_instance_groups }}"
  loop: "{{ __contents_filetree_controller_instance_groups.results }}"
  when: __contents_filetree_controller_instance_groups.results is defined and item.ansible_facts.controller_instance_groups is defined

- name: "Set Instance Groups Data Structure"
  set_fact:
    controller_instance_groups: "{{ __populate_controller_instance_groups }}"
  when: __populate_controller_instance_groups is defined
...
