---
- name: "Read Labels definitions"
  include_vars:
    file: "{{ item.src }}"
  with_filetree: "{{ filetree_controller_labels }}"
  when: item.state == 'file'
  register: __contents_filetree_controller_labels

- name: "Populate Labels list"
  set_fact:
    __populate_controller_labels: "{{ (__populate_controller_labels | default([])) + item.ansible_facts.controller_labels }}"
  loop: "{{ __contents_filetree_controller_labels.results }}"
  when: __contents_filetree_controller_labels.results is defined and item.ansible_facts.controller_labels is defined

- name: "Set Labels Data Structure"
  set_fact:
    controller_labels: "{{ __populate_controller_labels }}"
  when: __populate_controller_labels is defined
...
