---
- name: "Get list of files inside {{ filetree_controller_projects }}"
  find:
    paths: "{{ filetree_controller_projects }}"
    file_type: file
    recurse: yes
  register: __list_files_controller_projects

- name: "Read Projects definitions"
  include_vars:
    file: "{{ item.path }}"
  loop: "{{ __list_files_controller_projects.files }}"
  register: __contents_filetree_controller_projects

- name: "Populate Projects list"
  set_fact:
    __populate_controller_projects: "{{ (__populate_controller_projects | default([])) + item.ansible_facts.controller_projects }}"
  loop: "{{ __contents_filetree_controller_projects.results }}"
  when: __contents_filetree_controller_projects.results is defined and item.ansible_facts.controller_projects is defined

- name: "Set Projects Data Structure"
  set_fact:
    controller_projects: "{{ __populate_controller_projects }}"
  when: __populate_controller_projects is defined
...
