---
- name: "Read Settings definitions"
  include_vars:
    file: "{{ item.src }}"
  with_filetree: "{{ filetree_controller_settings }}"
  when: item.state == 'file'
  register: __contents_filetree_controller_settings

- name: "Populate Settings list"
  set_fact:
    __populate_controller_settings: "{{ (__populate_controller_settings | default([])) + item.ansible_facts.controller_settings }}"
  loop: "{{ __contents_filetree_controller_settings.results }}"
  when: __contents_filetree_controller_settings.results is defined and item.ansible_facts.controller_settings is defined

- name: "Set Settings Data Structure"
  set_fact:
    controller_settings: "{{ __populate_controller_settings }}"
  when: __populate_controller_settings is defined
...
