---
- name: "Get list of files inside {{ filetree_aap_teams }}"
  ansible.builtin.find:
    paths: "{{ filetree_aap_teams }}"
    file_type: file
    patterns: "{{ filetree_controller_include | default(omit) }}"
    excludes: "{{ filetree_controller_exclude | default(omit) }}"
    use_regex: "{{ filetree_controller_regex | default(false) }}"
    recurse: true
  register: __list_files_aap_teams

- name: "Read Teams definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_teams_definitions_item.path }}"
  loop: "{{ __list_files_aap_teams.files }}"
  loop_control:
    loop_var: __read_teams_definitions_item
  register: __contents_filetree_aap_teams
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_aap_teams"

- name: "Set Teams Data Structure"
  ansible.builtin.set_fact:
    aap_teams: >-
      {{
        __contents_filetree_aap_teams.results |
        rejectattr('ansible_facts.aap_teams', 'undefined') |
        map(attribute='ansible_facts.aap_teams') |
        ansible.builtin.flatten
      }}
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_aap_teams.results
...
