---
name: Test roles and modules
on: [push, pull_request]

jobs:
  ci_standalone:
    strategy:
      fail-fast: false
      matrix:
        galaxy_ng_version:
          - stable-4.2
          - stable-4.3
          - stable-4.4
          - stable-4.5
          - stable-4.6
          - master
    uses: "./.github/workflows/ci_standalone_versioned.yml"
    with:
      galaxy_ng_version: ${{ matrix.galaxy_ng_version }}
